version: 1
builder:
  configs:
    - documentation_targets:
        - TecoCore
        - TecoDateHelpers
        - TecoPaginationHelpers
        - TecoSigner
      custom_documentation_parameters: ['--include-extended-types']
      platform: linux
