//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022-2023 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoRegionGenerator.
// DO NOT EDIT.

/// Tencent Cloud region identified by Region ID.
public struct TCRegion: Equatable, Sendable {
    /// Raw region ID.
    public var rawValue: String

    /// Tencent Cloud service region kind.
    public enum Kind: Equatable, Sendable {
        /// Global service regions that are open and accessible within each other.
        case global
        /// Financial service regions that are isolated, yet accessible within each other.
        case financial
        /// Special service regions that are assumed to be fully isolated.
        case `internal`
    }

    /// Region type by data isolation.
    public var kind: Kind

    public init(id: String, kind: Kind = .global) {
        self.rawValue = id
        self.kind = kind
    }

    /// 华南地区(广州) / South China(Guangzhou)
    public static var ap_guangzhou: TCRegion {
        TCRegion(id: "ap-guangzhou")
    }

    /// 华南地区(深圳金融) / South China(Shenzhen Finance)
    public static var ap_shenzhen_fsi: TCRegion {
        TCRegion(id: "ap-shenzhen-fsi", kind: .financial)
    }

    /// 华南地区(广州OPEN) / South China(Guangzhou OPEN)
    public static var ap_guangzhou_open: TCRegion {
        TCRegion(id: "ap-guangzhou-open")
    }

    /// 华南地区(清远) / South China(Qingyuan)
    public static var ap_qingyuan: TCRegion {
        TCRegion(id: "ap-qingyuan")
    }

    /// 华南地区(清远信安) / South China(Qingyuan Xinan)
    public static var ap_qingyuan_xinan: TCRegion {
        TCRegion(id: "ap-qingyuan-xinan", kind: .internal)
    }

    /// 华南地区(深圳深宇财付通) / South China(Shenzhen Shenyu Tenpay)
    public static var ap_shenzhen_sycft: TCRegion {
        TCRegion(id: "ap-shenzhen-sycft", kind: .internal)
    }

    /// 华东地区(上海) / East China(Shanghai)
    public static var ap_shanghai: TCRegion {
        TCRegion(id: "ap-shanghai")
    }

    /// 华东地区(上海金融) / East China(Shanghai Finance)
    public static var ap_shanghai_fsi: TCRegion {
        TCRegion(id: "ap-shanghai-fsi", kind: .financial)
    }

    /// 华东地区(济南) / East China(Jinan)
    public static var ap_jinan_ec: TCRegion {
        TCRegion(id: "ap-jinan-ec")
    }

    /// 华东地区(杭州) / East China(Hangzhou)
    public static var ap_hangzhou_ec: TCRegion {
        TCRegion(id: "ap-hangzhou-ec")
    }

    /// 华东地区(南京) / East China(Nanjing)
    public static var ap_nanjing: TCRegion {
        TCRegion(id: "ap-nanjing")
    }

    /// 华东地区(福州) / East China(Fuzhou)
    public static var ap_fuzhou_ec: TCRegion {
        TCRegion(id: "ap-fuzhou-ec")
    }

    /// 华东地区(合肥) / East China(Hefei)
    public static var ap_hefei_ec: TCRegion {
        TCRegion(id: "ap-hefei-ec")
    }

    /// 华东地区(上海自动驾驶云) / East China(Shanghai Self-driving Cloud)
    public static var ap_shanghai_adc: TCRegion {
        TCRegion(id: "ap-shanghai-adc", kind: .internal)
    }

    /// 港澳台地区(中国香港) / Hong Kong, Macau and Taiwan (China)(Hong Kong, China)
    public static var ap_hongkong: TCRegion {
        TCRegion(id: "ap-hongkong")
    }

    /// 港澳台地区(中国台北) / Hong Kong, Macau and Taiwan (China)(Taiwan, China)
    public static var ap_taipei: TCRegion {
        TCRegion(id: "ap-taipei")
    }

    /// 北美地区(多伦多) / North America(Toronto)
    public static var na_toronto: TCRegion {
        TCRegion(id: "na-toronto")
    }

    /// 华北地区(北京) / North China region(Beijing)
    public static var ap_beijing: TCRegion {
        TCRegion(id: "ap-beijing")
    }

    /// 华北地区(北京金融) / North China region(Beijing Finance)
    public static var ap_beijing_fsi: TCRegion {
        TCRegion(id: "ap-beijing-fsi", kind: .financial)
    }

    /// 华北地区(石家庄) / North China region(Shijiazhuang)
    public static var ap_shijiazhuang_ec: TCRegion {
        TCRegion(id: "ap-shijiazhuang-ec")
    }

    /// 亚太东南(新加坡) / Southeast Asia(Singapore)
    public static var ap_singapore: TCRegion {
        TCRegion(id: "ap-singapore")
    }

    /// 亚太东南(曼谷) / Southeast Asia(Bangkok)
    public static var ap_bangkok: TCRegion {
        TCRegion(id: "ap-bangkok")
    }

    /// 亚太东南(雅加达) / Southeast Asia(Jakarta)
    public static var ap_jakarta: TCRegion {
        TCRegion(id: "ap-jakarta")
    }

    /// 美国西部(硅谷) / US West(Silicon Valley)
    public static var na_siliconvalley: TCRegion {
        TCRegion(id: "na-siliconvalley")
    }

    /// 西南地区(成都) / Southwest China(Chengdu)
    public static var ap_chengdu: TCRegion {
        TCRegion(id: "ap-chengdu")
    }

    /// 西南地区(重庆) / Southwest China(Chongqing)
    public static var ap_chongqing: TCRegion {
        TCRegion(id: "ap-chongqing")
    }

    /// 西南地区(贵阳) / Southwest China(Guiyang)
    public static var ap_guiyang: TCRegion {
        TCRegion(id: "ap-guiyang")
    }

    /// 欧洲地区(法兰克福) / Europe(Frankfurt)
    public static var eu_frankfurt: TCRegion {
        TCRegion(id: "eu-frankfurt")
    }

    /// 欧洲地区(莫斯科) / Europe(Northeastern Europe)
    public static var eu_moscow: TCRegion {
        TCRegion(id: "eu-moscow")
    }

    /// 亚太东北(首尔) / Northeast Asia(Seoul)
    public static var ap_seoul: TCRegion {
        TCRegion(id: "ap-seoul")
    }

    /// 亚太东北(东京) / Northeast Asia(Tokyo)
    public static var ap_tokyo: TCRegion {
        TCRegion(id: "ap-tokyo")
    }

    /// 亚太南部(孟买) / South Asia(Mumbai)
    public static var ap_mumbai: TCRegion {
        TCRegion(id: "ap-mumbai")
    }

    /// 美国东部(弗吉尼亚) / US East(Virginia)
    public static var na_ashburn: TCRegion {
        TCRegion(id: "na-ashburn")
    }

    /// 华中地区(武汉) / Central China(Wuhan)
    public static var ap_wuhan_ec: TCRegion {
        TCRegion(id: "ap-wuhan-ec")
    }

    /// 华中地区(长沙) / Central China(Changsha)
    public static var ap_changsha_ec: TCRegion {
        TCRegion(id: "ap-changsha-ec")
    }

    /// 华中地区(郑州) / Central China(Zhengzhou)
    public static var ap_zhengzhou_ec: TCRegion {
        TCRegion(id: "ap-zhengzhou-ec")
    }

    /// 东北地区(沈阳) / Northeast China(Shenyang)
    public static var ap_shenyang_ec: TCRegion {
        TCRegion(id: "ap-shenyang-ec")
    }

    /// 西北地区(西安) / Northwest region(Xi'an)
    public static var ap_xian_ec: TCRegion {
        TCRegion(id: "ap-xian-ec")
    }

    /// 西北地区(西北) / Northwest region(Northwest China)
    public static var ap_xibei_ec: TCRegion {
        TCRegion(id: "ap-xibei-ec")
    }

    /// 南美地区(圣保罗) / South America(São Paulo)
    public static var sa_saopaulo: TCRegion {
        TCRegion(id: "sa-saopaulo")
    }

    /// Returns a ``TCRegion`` with custom Region ID.
    ///
    /// - Parameters:
    ///   - id: Region ID.
    ///   - kind: Region type by data isolation. Defaults to `.financial` if region ID is suffixed with `-fsi`, else defaults to `.internal`.
    public static func custom(_ id: String, kind: Kind? = nil) -> TCRegion {
        TCRegion(id: id, kind: kind ?? Self.defaultKind(from: id))
    }

    public static func == (lhs: TCRegion, rhs: TCRegion) -> Bool {
        lhs.rawValue == rhs.rawValue
    }
}

extension TCRegion: CustomStringConvertible {
    public var description: String {
        self.rawValue
    }
}

extension TCRegion {
    /// Returns a Boolean value indicating whether a region is accessible from another.
    public func isAccessible(from region: TCRegion) -> Bool {
        self == region || (self.kind == region.kind && self.kind != .internal)
    }

    /// Returns the default region kind inferred from region ID.
    private static func defaultKind(from regionId: String) -> Kind {
        return regionId.hasSuffix("-fsi") ? .financial : .internal
    }
}
