name: API Breakage
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - '!**/*.docc/**'

jobs:
  api-breakage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          prefix: 'v'
          release-branch: 'main'
      # https://github.com/actions/checkout/issues/766
      - name: Mark the workspace as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: API breaking changes with last release
        continue-on-error: true
        id: diagnose
        env:
          TAG: ${{ steps.version.outputs.previous-version }}
        run: swift package diagnose-api-breaking-changes "${TAG}"
      - name: API breaking changes with main
        if: ${{ steps.diagnose.outcome != 'success' }}
        run: swift package diagnose-api-breaking-changes main
