name: API Breakage
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Package.swift'
      - 'Sources/**'

jobs:
  api-breakage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          prefix: 'v'
          release-branch: 'main'
      - name: Diagnose API breaking changes
        env:
          TAG: ${{ steps.version.outputs.previous-version }}
        run: swift package diagnose-api-breaking-changes "${TAG}"
