name: Build
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build.yml'
      - 'Package.*'
      - 'Sources/**'
      - 'Tests/**'
      - '!**/*.docc/**'
  merge_group:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
        swift:
          - '5.5'
          - '5.6'
          - '5.7'
          - '5.8'
        exclude:
          - os: macos-11
            swift: '5.8'
          - os: macos-12
            swift: '5.5'
          - os: macos-12
            swift: '5.6'
          - os: ubuntu-22.04
            swift: '5.5'
          - os: ubuntu-22.04
            swift: '5.6'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        if: ${{ matrix.swift != '5.8' }}
        with:
          swift-version: ${{ matrix.swift }}
      - name: Setup Swift
        uses: slashmo/install-swift@v0.4.0
        if: ${{ matrix.swift == '5.8' }}
        with:
          version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  build-with-docc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -Xswiftc -DBUILDING_DOCC
