name: Build
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Package.*'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
        swift:
          - '5.5'
          - '5.6'
          - '5.7'
        exclude:
          - os: macos-12
            swift: '5.5'
          - os: macos-12
            swift: '5.6'
          - os: ubuntu-22.04
            swift: '5.5'
          - os: ubuntu-22.04
            swift: '5.6'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Build (release)
        run: swift build -c release
